- enhancedsteam.js
The currently used link syntax for Steam Gifts links on profiles [may be subject to change in the future](http://www.steamgifts.com/go/comment/j5vhyqg), so this pull request updates the format to the new syntax.
> Update to Steam Gifts link syntax

- enhancedsteam.js
Works with both old and new styles, and replaces the name to keep the full title.
The current code doesn't update either of the titles on the [main account page](https://store.steampowered.com/account/), and also breaks page titles on the [family sharing](https://store.steampowered.com/account/managedevices) and [family view](http://store.steampowered.com/parental/set) pages.
> Update account to community name for new style

- enhancedsteam.js
Fixes bug #680 where whishlist items could not be removed from the store
page.
Removal request must use user's "Custom URL" In some cases this will not
match their profile or account names.
> Fixed wishlist removal from store page

- enhancedsteam.js
With SSL forced on (e.g. HTTPS Everywhere), this will fail to redirect and cause an Access Denied error.
> Don't use www on achievements compare link

- css/enhancedsteam.css
- enhancedsteam.js
- js/options.js
- localization/de/strings.json
- options.html
Added vote preview and fading of voted items on Greenlight browsing pages, added one option for each (both off by default), including german translation. Also converted it to jQuery instead of plain JS and improved it a little (simpler code and better performance compared to my original).
I'm not really happy with the option names, but I couldn't think of any better. Maybe someone else can.
Extensively tested, no known problems (except for not being able to use any API).
> added vote preview on Greenlight browsing pages

- enhancedsteam.js
Total Spent feature only appears on `.../account/store_transactions/`, but should also appear on `.../account/` (and with or without trailing slash), since they point to the same page.
> Fix: enable Total Spent feature for all apropriate URLs

- css/enhancedsteam.css
(New PR from branch fix-778 to keep my dev branch clean.)
This restores the original selection background color for entries that are both selected and highlighted, since in my opinion the selection takes precedence over the highlighting.
> FIX: #778 (Selected highlighted live search result looks like unselected one)

- enhancedsteam.js
Get correct language by checking which script is loaded. This is more reliable than using the cookie, since the cookie might not exist and could be ignored when changing the language using the URL parameter.
> FIX: #776 (Language warning appears too often)

- enhancedsteam.js
When spaces are used as the thousand separator, any item for which a coupon is available will have its original price incorrectly parsed and ends up being replaced with an incorrect discounted price.
In case it's not obvious, the last three digits of both the original price and the discounted price were accidentally truncated when applying the coupon.
> FIX: Price with spaces getting parsed incorrectly when applying a coupon

- enhancedsteam.js
Start from the appropriate page when reloading after endless scrolling on Greenlight by updating the page parameter in the URL while scrolling. (I thought I already implemented this in 897c3a3024e9c4a1e290a7a2e7a93d919cbd3be2, but I only started it.)
> Improve reloading with endless scrolling Greenlight

- enhancedsteam.js
Use the new language detection introduced in c5dbaf2df4754c24ac837f7a2f9168a3ada1a51a for everything, not just the language warning.
(For explanation see PR #785)
> Improve language detection

- enhancedsteam.js
Prevent the same bundle being displayed more than once on the same page under certain circumstances.
As a side effect games included a bundle are now sorted by name.
> Prevent duplicate bundles

- css/enhancedsteam.css
- enhancedsteam.js
Validates price input via regular expression, instead of only accepting JS floats.
Allows comma and period as decimal separator and comma, period and space as thousands separator, as well as currency symbols before and after the number.
Invalid input is indicated by red border.
> FIX: #811 (Market relist only supports period as decimal separator)

- enhancedsteam.js
- localization/en/strings.json
Word order can be different in other languages.
> Improve 'Buy <bundle name>' header translation

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
Sort order will be remembered until it is changed again. Works on all friends lists, not only the own one.
Looks just like the option for sorting achievements by date unlocked, but is implemented completely different, so it doesn't interfere with the Manage Friends List functions.
> Add option on friends pages to sort friends by last online

- enhancedsteam.js
Dynamic Greenlight and endless scrolling now wait for remembered filter options to be restored, so they don't slow down the process.
Greenlight items are dynamically replaced instead of a full page reload.
> Improvements for remembering Greenlight filter options

- enhancedsteam.js
Javascript that came with new items wasn't loaded.
> FIX #819 (No preview popup after endless scrolling on Greenlight)

- css/enhancedsteam.css
CSS class "es_each" is used for bundle info and multi-pack split, I checked both cases with my change.
> FIX #827 (Bundle price misaligned)

- enhancedsteam.js
Source text is escaped twice, so extra unescaping is required.
> FIX #829 (escaped HTML entities in description on carousel)

- enhancedsteam.js
The fix seems obvious and low-risk, but please check it for yourself anyway. ;)
> FIX #831 (Continuous scrolling doesn't reset after changing sort order)

- enhancedsteam.js
Fewer requests, less JSON parsing, fewer failures when ES API is unavailable.
Didn't change nearly as much as the additions/deletions suggest. I mainly moved some code and changed the indentation accordingly, which makes it look like a lot was changed.
> Only load Early Access data when necessary

- changelog.txt
Continuous scrolling now DOES reset after changing the sort order. The problem was that it didn't before.
My PR title (#832) was probably unclear, because I copied it from the issue (#831).
> Fixed mistake in changelog

- css/enhancedsteam.css
This fix will only stay active for the duration of the sale and might even automatically work with future sales.
> Fix broken homepage tabs with Fall Sale 2015 design

- enhancedsteam.js
Adds a way to reliably detect the user's currency, which is used in all places where a monetary value is displayed. It is not used for parsing prices from the purchase history, since that is currently not possible.
> Improved currency detection

- enhancedsteam.js
use getStoreRegionCountryCode() to get the correct data from the Steam API
> FIX #903 (new currency detection doesn't work reliably)

- enhancedsteam.js
Unescaped "$" in the regex from ``currency_symbol_from_string`` function caused CLP currency being detected as PHP, as seen in #872.
> Fixes CLP currency detection

- enhancedsteam.js
- js/options.js
Crowdin export can now be changed to skip untranslated strings.
Prevents bugs like #825 and #826 and makes development for non English speaking developers easier.
> Load untranslated strings from english localization

- css/enhancedsteam.css
- enhancedsteam.js
Didn't take into consideration the button might overlap the menu when
there is no featured app on the main page. It should be fine now, the
page won't shift/move down anymore when the "Customize" button is
inserted.
> Move the button up only if there is no featured app

- enhancedsteam.js
Using steam://store/ command won't open the app page in client if Family
View is enabled, it will just show the library.
This seems to be a bug on Steam's side as there is no point in not
showing an app's page since you can still manually access it.
> FIX: App page won't open if Family View enabled

- enhancedsteam.js
Looks like **market_hash_name** is not always present, in which case
**market_name** is used instead. We'll do the same.
> Fixes #984

- enhancedsteam.js
This should fix #867.
Chinese Yuan and Japanese Yen are both using symbol ￥, so it's not a good way to detect currency type from its symbol.
Steam gives a meta tag in HTML to show the currency (mentioned in #939, thought that bug is still not fixed right now), so we can just use it.
\* Updated: typo
> Fixed CNY has been detected as JPY

- js/options.js
There was no prompt when trying to reset the options since the locale variable was not set/available in global scope.
> No prompt when trying to reset options

- css/enhancedsteam.css
- enhancedsteam.js
* Most of the design is now handled just by CSS
* You can toggle between Default and Binder View without the page
reloading
* Binder View sticks when navigating between badge pages
* Fixed a small bug where the badge title would would be pushed on the same level with the badge image
> Redone add_badge_view_options()

- enhancedsteam.js
* Instead of caching parts of the data from
http://store.steampowered.com/dynamicstore/userdata/ we now cache it whole and
pick what we need from it later. This results in less code and less
requests when needing that data
* The owned apps ids required for "Launch Random Game" feature are also
pulled from this data now instead of calling the ES API
To ensure the cache is even fresher we could add an option to force
updates when actions are taken. Such as wishlist changes, ignoring apps,
buying apps etc.
> Unified promises requesting for dynamicstore

- enhancedsteam.js
While in search with endless scrolling enabled the page hangs while scrolling. Chances are this is not so noticeable on faster machines but is quite noticeable on a laptop with an i5 processor.
After loading more and more results the issue starts to reoccur, however, is considerably less noticeable. It seems to be related to the MutationObserver having to monitor so many items at once, every time it ticks the page hangs for a few ms.
Here are two videos(_both recorded at 60fps_) with the issue, before (_please notice the scrollbar height, it's not because there are results loading as I scroll_) and after:
https://streamable.com/je60
https://streamable.com/4dvx
> Fix page hanging while scrolling in search

- enhancedsteam.js
* Added ability to sort by "rank", "name", "price" or "discount" without
the page reloading
* The "discount" sorting is faster
* The state of the sorting is saved in a cookie (as Steam does) and
works for "discounted" too
There is no live sorting for "date added" since there is no data to work
with on the page and didn't wanted to make a request for it. So this one
works as before.
> Wishlist sorting improvements

- enhancedsteam.js
* Optimized code so there is no looping over each "Remove" link, addition or removal or elements, this also causes for the ajax "click" event to be applied for all links in one go.
* When possible (if store session id is found in cache) the request of removing the item is done via the API which is much faster.
> Wishlist remove optimizations

- enhancedsteam.js
- localization/en/strings.json
This allows for previewing any background directly from market on your
profile page without having to change anything.
Useful for those that look for a nice bg image for their profile but
don't want to use 3rd party sites or login in ES everytime when setting
a custom bg.
> NEW: Preview any background directly from market

- enhancedsteam.js
* no longer loops over nodes that were already processed
* condensed "appid" retrieval/check and we no longer search for the app header img with every "if" statement
* while it might be just micro optimization the code execution should be faster
> check_early_access() optimizations

- css/enhancedsteam.css
- enhancedsteam.js
* fixed a bug with labels on radio inputs that have "click" bound to them which trigger the "click" event twice and basically causing the code to also be ran twice
* no longer uses "each" over wishlist rows, which makes things faster
* slightly decreased the vertical movement of the page when the filter options are injected
> add_wishlist_filter() optimizations

- enhancedsteam.js
At the time I'm writing this the ES API is down and the retrieval of
currency conversion rates fails making dependent functions to also fail.
So from now on when this happens we fallback to cache.
> Currency conversion rates fail safe

- css/enhancedsteam.css
- enhancedsteam.js
This only prevents the items overflowing if something goes wrong with
the width calculations for #main_cluster_scroll but won't fix the issue that
led to that.
> Prevent carousel items overflowing

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
When accessing the Wishlist, having many wishlisted apps can make the
page freeze or stutter for a few moments, which sucks since it looks as
it's done loading and ready to interact with. So, if there are too many
items, we display a button which will load the wishlist total when/if
needed.
(This alone doesn't fix the stuttering issue completely but it helps)
> add_wishlist_total() optimizations

- enhancedsteam.js
When requesting steamcommunity.com/profiles/0/ via AJAX Chrome automatically attaches the cookies to the request, Firefox doesn't seem to do the same.
> Force credentials

- enhancedsteam.js
- fixed app images not loading when selecting "Installed games" filter
- added space between "total size" and "total time" blocks 
- use localized text for "hours"
> FIX: App images not loading when applying filter

- enhancedsteam.js
There seems to be some changes to the way the language is set. A simple
cookie change on steamcommunity.com no longer works and there is a
request to http://steamcommunity.com/actions/SetLanguage/ involved.
This is needed most likely because now the language selection is shared
with the Steam app.
To fix this we'll simply use Steam's method for changing the language.
> FIX: Language reset not working

- css/options.css
- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
*Many steps have been automated, code in options.js was cut by half*
- options under "General" tab that had something to do with 3rd party
sites were moved separately since the options list got quite big and
confusing
- redone the way settings are saved and initialized
- redone the way localized strings are inserted
- redone the way navigation tabs work to show their content
- removed unnecessary functions
- several minor touches
All these changes ammout to alot of repetitive code being removed making it easier to maintain.
Also adding an option is now much more easier, basically you add the HTML needed for the input and a new entry in "settings_defaults".
> Cleaned and simplified code in Options page

- css/enhancedsteam.css
- under "Current Players" numbers overlap for games with many players
such as Dota 2
> Adjusted font size so numbers don't overlap

- css/enhancedsteam.css
- enhancedsteam.js
- fixed a bug where the highlighting process would run over already
highlighted items
- apps text is highlighted diferently to make it easier to read
- in "add_achievement_comparison_link()" when requesting for the stats
page the required data is memoized so there are no more subsequent
request are for the same page
-  "add_achievement_comparison_link()" is only be called on owned apps
- added a mutation observer for discussion pages that load paginated
content via ajax when removal of links filtering is enabled
> Activity page highlighting and link filter optimizations

- css/enhancedsteam.css
- enhancedsteam.js
- uses dynamic store data to check whether the app is wishlisted or owned
- dynamic store data is invalidated (and later refreshed) after the app is wishlisted
- the header is highlighted as "owned" or "wishlisted" when needed
- tweaked "dynamicstore_promise" to further ensure the data we receive is fresh after it was invalidated
> Wishlist button in community hub optimizations

- enhancedsteam.js
There were some issues with owned apps returned from dynamic store data
where video didn't work properly and it would propose apps that are not
directly playable such as DLCs... So we go back to using the ES API for
providing the list with playable games.
> launch_random_button() revert to using ES API

- css/options.css
Firefox doesn't support the (webkit) prefixed `linear-gradient`, so was rendering the options page with no background. I've added the standard/un-prefixed syntax to fix this. Chrome and Safari no longer need the prefixed version either, but I'm not sure what browser versions you're supporting, so I've left the prefixed version in as a fallback.
> Add prefix-free background gradient for the options page

- enhancedsteam.js
- fixes an error when not logged in (_and there is really no need to have initialized it every time the page loads since "Launch Random Game" feature is not so often used_)
> Trigger "owned_playable_promise" only when needed

- enhancedsteam.js
- purchase dates are shown in the language currently selected
- on the licenses page app names can contain text strings that can cause name miss matching, so we remove them  (_wish there were appids so we no longer have to compare names..._)
> Multiple language support for purchase dates

- enhancedsteam.js
- Fixes #1122
Note:
@jshackles all strings should be wrapped in single quotes to avoid such situations, I was lazy and let it _slide_ when I've recoded **inventory_market_helper()**.
However, instead of going through all code take your time if you can and setup a linter and include this rule (is pretty much the standard so I'd be surprised if is not already like that by default). It can be setup so it follows most of ES's coding style so there won't too many warnings but there are still a few more things that need to be changed for better standards.
> Wrap string in single quotes

- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
Achieves feature #719.
Ideally, I wanted to just check the setting in the add_empty_wishlist_buttons function, however the settings do not appear to be available in that context. Alternatively, I wanted to call .remove() on the button in remove_empty_wishlist_button()... but the button is not on the page at time of that method invoking.
So, instead we're adding a flag.
Alternatively (if we didn't want the global var), we could add css to the page in 'remove_empty_wishlist_button'.
> #719 - Option to hide/remove "Empty Wishlist" button

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
Added ability to exclude user tags in search.
This is based on the fact that negative tag numbers in the search url
are excluded, and the "Narrow by tag" box already includes all(?) tags for me to harvest. :)
I would have liked to add the box after the "Narrow by tag" box, but since it has no id it would have to be done by index or manual navigation through the DOM.
I considered that too flaky and prone to breaking so it's directly below the "hide elements" box.
> Exclude tags in store search

- enhancedsteam.js
Fixed a bug where empty data was being returned even after the user logged in correctly due Valve's aggressive caching.
> dynamicstore_promise() cache fix

- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
- made the display of Steam wallet balance in header an option
- the balance is pulled from store.steampowered.com/_about/_ as the page
is smaller and faster to load
> UPDATE: Steam wallet balance in header as option

- enhancedsteam.js
The list of games this removes is on the issue #1085. It's really just the pinball games that are the problem.
> FIX: ignore season packs

- css/enhancedsteam.css
- fixes username and alias dropdown not being clickable while having "Holiday 2014" style enabled
- fixed a background spacing issue with the main content container
_before_
_after_
> FIX: #1210

- enhancedsteam.js
A check was readded in order to fix this bug and another one where buttons with wrong prices would be shown for a few moments.
The bug manifests when clicking multiple items in inventory before one or more had a chance to finish loading the pricing information. When done loading the information is inserted without checking whether it belongs to the item currently selected.
_Video with the bug https://streamable.com/63ev_
> FIX: Multiple spaces between Quick and Instant sell buttons

- enhancedsteam.js
- the price is no longer read from input by us, but by Valve's ```GetPriceValueAsInt()``` function and the sell price is directly derived from the information supplied by Valve's ```CalculateFeeAmount()```. This way at least we know that the data is manipulated as close as Valve does it.
> FIX ATTEMPT: Relist price bug

- LICENSE
- README.md
Adding a LICENSE file allows Github to automatically recognize which license the project uses and it allows users and developers to easily see which exact version of the license is used.
The README didn't specify the exact version of the GPL, which probably means the user can always choose the current version of the license. Changing it to GPLv3+ retains the same meaning while avoiding confusion.
> Added LICENSE

- enhancedsteam.js
I have too many games on my account, and every now and then when I open a certain game's store page my browser freezes as Enhanced Steam tries to load the purchase date data from the licenses page. When this happens, it usually freezes for about 16 seconds or so.
This PR should remedy that. I had been testing with this a bit and the browser freeze is pretty much negligible now (it usually lasts for roughly one second). The main reason this fix works, is because of the extra selector when querying the response body of the HTTP request. Querying the `#main_content` first before looking for the `.license_date_col` elements seem to calm jQuery down a bit.
> Improves performance when opening a store page

- css/enhancedsteam.css
- enhancedsteam.js
- fixed a bug with profiles using the Holiday theme (not via ES). On
these profiles the theme graphics are not loaded or shown, instead the
default theme is still displayed, so we avoid adding the CSS fixes for
the theme,  otherwise it would break the default design.
_(Profile example: [https://steamcommunity.com/id/steamdb_wendy/](https://steamcommunity.com/id/steamdb_wendy/))_
> FIX: Holiday profile style bug

- enhancedsteam.js
- g_sessionID is still available even when logged out so we need to make sure we are logged into the Store (since getting randomly but temporarily logged out of Store is a common occurrence)
> get_store_session() extra login check

- css/options.css
- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
- large wishlists can result in hundreds of KBs loaded everytime, this could be solved using cache (TODO?) but is a bit more tricky, and having things as options is always good
> UPDATE: Wishlist link on profiles as option

- js/options.js
- fixed a cache limit error due to triggering "change" too many times and thus causing `save_options()` to trigger aswell every time
> Fixed a cache limit error

- enhancedsteam.js
- it resulted on functions being executed while the user was logged out and then errors are thrown
> FIX: load_inventory() reponse when logged out

- enhancedsteam.js
- link filter wouldn't work for links such as those in groups overview
> FIX: Link filter in groups overview

- enhancedsteam.js
_Redone add_lowest_market_price() in order to address some issues and
make some optimizations._
- the requests for prices are no longer made all at once, but rather 5 at
a time. This helps avoid being blocked by Valve for too many concurent
requests
- the prices are memoized; if the price for an item was already pulled
it won't be requested again
- if a price request fails (due to being blocked for eg.) no subsequent
requests will be made
- fixed a bug which caused the price requests to be re-issued everytime
listings were sorted
- fixed a bug which caused ES to break while being logged out and viewing the market
> UPDATE: add_lowest_market_price() code

- enhancedsteam.js
- localization/en/strings.json
_Redone the functions for emptying the wishlist and ajax removal of apps
from wishlist_
- removal requeste are done in batches of 5 at a time, this helps avoid
browser limitations happening when attemptin to empty large wishlists
- the requests are done via store API, but if they fail due to many
requests it will fallback to using the old method
- Valve's more user friendly modal prompt is used to inform the user
> UPDATE: Empty wishlist code

- enhancedsteam.js
- fixed a bug where the process of leaving all groups could be paused if the page/tab was not focused for some time
> FIX: Group leaving pause

- enhancedsteam.js
If the user owned one or more cards the amount would end up being added
to the card's name, causing mismatches.
> FIX: Card name mismatch

- enhancedsteam.js
Fixes #1374
(_the decoding and re-encoding of ampersands is intentional, just in case
there are decoded ampersands in  a card's name_)
> FIX: #1374

- enhancedsteam.js
Two step approach:
1. Validate the incoming response for the existence of the `data["urls"]["bundle_history"]` property before putting it into a link to avoid the error ("(Info)" link will be lost). In addition the `.toString()` call was removed as it should already be a string when returned from the API (correct me if I'm wrong here).
2. Use an alternative property `data["urls"]["bundles"]` found in the response to seemingly restore "(Info)" link functionality back to normal. `data["urls"]["bundle_history"]` is still checked if the new property doesn't exist or is empty.
----
Issue reference: #1382
> FIX #1382 (Pricing history for games with bundles do not load)

- enhancedsteam.js
When searching through the market place, any search term not in the item's name would be appended to the URI as ('?filter=term'). The regex to extract the name from the URI also extracted that part, with (.+) matching everything up to the end of the URI and (\?)? always matching zero question marks. The fixed regex instead matches non-greedily up to the first question mark or end-of-line, whichever comes first.
> Fixed regex extracting market item name from URI

- enhancedsteam.js
Browsing **https**://steamcommunity.com will provide a link to **https**://astats.astats.nl in the sidebar leading to a blank page; leaving the impression it's down as it does not support https yet.
**Example:**
https://steamcommunity.com/id/luchaos/ 
leads to
https://astats.astats.nl/astats/User_Info.php?steamID64=76561197962872631
which will not load. (yet)
I'd reverse that as soon as AStats does support https (_https only, go!_) - until then this change makes it a bit more convenient to browse.
> AStats non-schema-agnostic link

- enhancedsteam.js
- simplified 'gameAppID' regexp
- fixed 'cardType' regexp
- fixed button showing on Steam listings such as 'Sack of Gems'
> FIX: add_badge_page_link() regexps

- enhancedsteam.js
- fixed a bug where JSON.parse() would fail and break ES if the returned data was not in JSON format
_(Early Access API would return 'Too many requests'(or something like that) and 503 errors. It was fixed by the time I've submitted this tho)_
> FIX: EA promise JSON parse fail

- enhancedsteam.js
Since the ES API server seems to support HTTPS for all requests, this shouldn't change anything for most users, but it would greatly reduce conflicts with _HTTPS Everywhere_. I've tested this in Chrome for almost two weeks with _HTTPS Everywhere_ disabled to ensure it won't cause any problems for regular users.
Although some rare problems might persist for _HTTPS Everywhere_ users, I consider the three issues mentioned in my commit message (#1319, #1432, #1445) fixed, because this is probably the best we can get without Steam allowing HTTPS for all API requests (or us proxying them).
I'm not convinced the conflicts with _HTTPS Everywhere_ are our fault, but if we can easily fix (or at least improve) them, we should do so.
> Use HTTPS for ES API requests

- css/enhancedsteam-firefox.css
This is a port of https://github.com/jshackles/Enhanced_Steam_Firefox/pull/115 into the main Enhanced Steam repo, per @jshackles's comment in jshackles/Enhanced_Steam_Firefox#114:
> Since Mozilla keeps changing how these relative paths load, I believe your idea of manually specifying an https protocol sounds prudent. Feel free to create a pull request with these changes in enhancedsteam-firefox.css in the dev branch here: https://github.com/jshackles/Enhanced_Steam/tree/dev
@c12h did the work here, I'm just porting over the PR.
> Use https-qualified URLs for platform images in FireFox

- options.html
This fixes HTML parsing issues that can be seen in Firefox when viewing the source of the options page.
Of course, the best way to prevent something like this happening in the future would be to switch the options page to [XHTML](https://developer.mozilla.org/en-US/docs/Glossary/XHTML).
> Fix HTML parsing issues

- enhancedsteam.js
For most European countries sorting by price currently works incorrectly in wishlist if discounted price contains decimal separator (which is comma instead of dot), so if there are 2 games with discounted prices 75,5 and 100 accordingly, they will be sorted vice versa, because parsing function currently returns 755 instead of 75.5
> Updated wishlist sorting by price if discounted price has decimal separator

- enhancedsteam.js
This will clean up the error message described in jshackles/Enhanced_Steam#1520
> $.fn.firstText() errors when it doesn't have enough input

- enhancedsteam.js
This should remediate jshackles/Enhanced_Steam#1494 if the $sideMarketActs.append() lines that are commented out in the Firefox repo around 5260 are re-enabled. I don't know what the original bug was, testing with the current jshackles/Enhanced_Steam_Firefox repo showed $.ajax() wasn't sending Referer: or Origin: headers and consequently Steam was replying with a 400 Bad Request response (or without the necessary CORS headers). Changing to Fetch and setting the headers now receives the usual mix of 200 and 502 ("There was an error listing your item, try again later.") responses.
The Fetch API is available in Chrome 42+, Firefox 39+ and Edge 14+ (https://caniuse.com/#feat=fetch)
> Changed quicksell to Fetch API

- enhancedsteam.js
Hi @jshackles,
last pull request #1493 I created fixed issue for me as I have € as a currency, but my friend from Russia reported that issue still exists in his wishlist. Turned out they have '.' character in a currency display name (for instance, that's a valid price display - 161,85 pуб. ), so additional fix was required. Now I checked all the currencies there are, work as intended.
> Fixed wishlist sorting by price for Russian rubles

- enhancedsteam.js
**As of today AStats has SSL and supports https links.** 
Browsing https://steamcommunity.com will link properly to https://astats.astats.nl again and work as intended.
As promised in https://github.com/jshackles/Enhanced_Steam/pull/1406, this reverts links back to being schema agnostic.
> UPDATE: AStats schema agnostic link (revert)
