- enhancedsteam.js
Used this to encode to entities: http://stackoverflow.com/a/28747939/2016041
jsperf test here: http://jsperf.com/html-entity-encoding
> Fixed #705 for other characters

- enhancedsteam.js
When user click on "Empty Cart", he got error "Something wrong with your cart" and this error repeats every use the cart functions (such as adding). This is a "shoppingCartGID" cookie issue. After "Empty Cart" action it goes to "0", this is not correct. "shoppingCartGID" should be deleted permanently.
> Fix Cart Issue

- README.md
Adds a link to the chrome webstore, and detailed instructions for installing manually.
> Update the README.md for better install instructions

- enhancedsteam.js
This should fix #759.
I hope you don't mind that I added a new parameter to the `check_early_access` function for callback stuff. The old solution which rely on using `setTimeout` doesn't look that great (even though it works).
> FIX: Missing EA banner on some Steam Community pages

- enhancedsteam.js
Always loads gift inventory and coupon inventory in English, so detection works correctly.
On app pages the coupon inventory is loaded in user language to correctly display the coupon message.
> FIX: #792 (gifts & coupons not detected for non-english users)

- enhancedsteam.js
Always position popup relative to the container
> FIX: #803 (Customize popup misaligned when homepage tab row is wrapped)

- enhancedsteam.js
Greenlight cache is now updated for each item individually.
Adds a better cache interface, that can be reused for #839.
> FIX #842 (Not all Greenlight items are cached when scrolling too fast)

- enhancedsteam.js
Partially reverted 5f0aa8371c023452508b77be05bb6d01f3d0faa2, replaced with cleaner fix.
This version allows fewer invalid numbers to be entered.
> FIX: starting relist with sep (improved)

- css/enhancedsteam.css
- enhancedsteam.js
Slightly adjusted look and feel of ES menu so it's more similar to the account menu. (Added fading and highlighting.)
> Improved look & feel for ES menu button and popup

- css/enhancedsteam.css
- enhancedsteam.js
Fixes two problems with the achievement bar in the game list
> Fixes for achievement bar in game list

- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
Steam offers the same functionality (although slightly different)
> Remove function to disable greenlight autoplay

- enhancedsteam.js
> Add getStoreRegionCountryCode() that reads country code from fakeCC over steamCountry

- enhancedsteam.js
Should probably fix (at least) #942, #939, #938?
> Correct county to country to fix country detection

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
Features:
- the ability to leave individual, multiple or all groups at once
- the option of re-joining a group after leaving it in case you left a
group by mistake
- per group row action progress indicator
- replaced Steam's way of leaving groups using new method to avoid
redirects
- all requests are done via AJAX so no redirects at all
TODO: Localise strings
> NEW Feature: Leave multiple groups at once

- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
new option in community section, disabled by default
> Don't automatically filter guides by language (resolves #859)

- enhancedsteam.js
Using chrome.storage.local allows the currency cache to be shared between HTTP and HTTPS.
The add funds page seems to use the same metrics as the store pages to determine the currency, can be accessed via HTTP and HTTPS, even when the user isn't logged in, and contains an unambiguous ISO currency code. This means it should probably even obsolete the recently added option to manually select a currency. To be safe I left the manual option and the Half-Life 2 store page check in for now as fallbacks.
> Improved currency detection and cache

- enhancedsteam.js
The selector changed from "my_market_listings**onhold**_number" to "my_market_listings**toconfirm**_number".
Also we should consider changing "hold_total" locale string from "Total on hold" to "Total awaiting confirmation" or something like that.
> "Total on hold" section has changed

- enhancedsteam.js
> Replaced space indents with tabs

- enhancedsteam.js
@seeeeew I hope that's what you meant :smile:
> Removed a $ by mistake in 54c93c4

- enhancedsteam.js
* Fixed a bug where the promise failed if the user had no ID set for his profile ( see #1002 )
* Added some utility variables
> Fixed signed_in_promise not working properly

- enhancedsteam.js
Fixed a small bug where the buttons would still get inserted if there was an error on groups page.
> Fixed a small bug when groups page has error

- css/enhancedsteam.css
- enhancedsteam.js
* Fixed a bug where the description for the first item in carousel
wouldn't get it's height adjust until scrolling occured.
* There is no more JS used for adjusting the height of elements, it's
handled by CSS.
* The description is nicely revealed by an animation.
> Fixed a bug with carousel description

- enhancedsteam.js
- localization/en/strings.json
As suggested in #989
Also includes a partial fix for the friend chat window not opening when
the chat popup was opened originating from a HTTP page (this happens due
to cross-origin policy).
> NEW: Send message dropdown options

- enhancedsteam.js
* Removed predefined protocol for "dropdown" icon
* Add "rgChatStartupParam" only when not browsing over HTTPS already
> Chat dropdown optimizations

- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
Resubmitted from #467 and #566.
Inspired by this userscript from Armada: http://userscripts-mirror.org/scripts/show/72037
> ADD: An option to skip the "Got Steam?" modal window

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
As suggested on Steam subreddit.
_I really couldn't find a way of directly changing the background with
just one request without losing other settings. If anyone is aware of
such a method let me know and I'll make the required changes._
> NEW: Set background from inventory

- css/enhancedsteam.css
- enhancedsteam.js
* Moved the "Add to wishlist" button
* Reduced opacity of platform icons
> Wishlist UX improvements

- enhancedsteam.js
Serve background preview images from a domain that supports HTTPS
> Background preview images HTTPS support

- css/enhancedsteam.css
- enhancedsteam.js
* Added option as button on media player to enable/disable HD on videos
* Sped up the media slider animation
* Fix a bug with media slider where the scrollbar wouldn't get adjusted properly
> NEW: Option to view videos in HD

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
* add option to filter games in Wishlist
* removed "game.css"  inclusion required for "wishlist total"design due
to conflicts and added the required statements to ES's main css file
* some CSS cleanup
> NEW: Filter games in Wishlist

- enhancedsteam.js
* don't show "Set as Background" in other's inventory
* serve "throbber.gif" from a HTTPS compatible domain
> Don't show "Set as Background" in other's inv.

- enhancedsteam.js
* the descriptions are pulled from **store.steampowered.com/apphover/** which is considerably faster and smaller in size
* renamed some vars to not confuse them
> add_carousel_descriptions() optimizations

- css/enhancedsteam.css
- enhancedsteam.js
* added a missing "}"
* fixed a bug that might falsely trigger "add_birthday_celebration()" when multiple accounts are used
> Added missing "}" in CSS and fixed a bug

- enhancedsteam.js
* finds and replaces the images faster
* serves the images from a HTTPS compatible domain
* images now have appropriate dimensions and aspect ratios
> fix_wishlist_image_not_found() optimizations

- css/enhancedsteam.css
- enhancedsteam.js
* saves HD player state and videos are loaded automatically in HD if needed
* videos are set to HD when expanding the slider for the first time after loading the page
* code was optimized so that the HD options are not initiated unless the videos are set to "Auto play" or selected to play
__________
* the expand/contract slider tool-tips are initiated only once, at page load
* code for side details was optimized so details are not created until the slider is expanded by the user or unless is detected as expanded after the page was loaded
* slightly increased animations speed
> Save player HD state

- enhancedsteam.js
* faster wishlist count on profiles
* replaced a ";"
> Faster wishlist count on profiles

- enhancedsteam.js
- localization/en/strings.json
This is only a very rough implementation of it, with very crude copy-pasting and adapting of the necessary bits to make it work. Please have a look and let me know if you'd like anything changed right now, and after that, or when you don't see anything obvious, i'm open to deduplicating it and the discount sorting function; or you can merge immediately. However you like it.
> implement wishlist sorting by currency value of discount

- css/enhancedsteam.css
- enhancedsteam.js
Optimized the code overall to go better with the latest changes:
* simplified  and optimized functions dealing with sorting by absolute
discounts to run faster
* moved the absoulte discount text in the same block with the percentage
discount
* better spaces cleanup inside "#wishlist_sort_options"
* faster more reliable sort links build upon load
* removed reset_sort_links()
> add_wishlist_discount_sort() optimizations

- css/enhancedsteam.css
Store's main menu would inherit some undesired styling properties
> Fixed styling affecting main menu

- enhancedsteam.js
*been getting some errors from this when accessing [http://steamcommunity.com/my/followedgames](http://steamcommunity.com/my/followedgames)*
> Check if there is a steam id

- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
(*While is a useful security measure the fact that it still filters popular site such as Twitch is annoying...*)
* option to disable links filtering
* small optimization on skip_got_steam() function
> Option to disable links filtering

- enhancedsteam.js
* check if we actually are on a greenlight page
> FIX: Null errors in endless_scrolling_greenlight()

- css/enhancedsteam.css
- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
* the multiple buttons bug should be completly fixed as now there is a
check of what item is selected and for which item the buttons are
attempted to be inserted
* price data pulled by ES is stored as HTML data to avoid doing
subsequent requests for the same item
* forced credentials when changing background from inventory
* added a check if the current inventory belongs to the user viewing it
* added a check if currently selected item is a booster pack
* added a new function to make it easier to create MutationsObservers
* improved overall code readability
> inventory_market_helper() optimizations

- css/enhancedsteam.css
- the progress indicator to no longer overflow the main progress bar
container when is at 1%
- fixed the progress indicator being square when there is an error
- added a nice subtle glow to the indicator when is complete
> Improved progress bar design

- enhancedsteam.js
- "ea_promise" will return cached data immediatly regardless of it's freshness, and try to update the cache after in the background. This ensures there are no delays when cache has expired due to waiting for ES API to respond or fails when ES API is down
- "dynamicstore_promise" is now aware of when Valve invalidates dynamic user data and refreshes it's cache
> "ea_promise" and "dynamicstore_promise" cache optimizations

- enhancedsteam.js
- "dynamicstore_promise()" will return cached data when not browsing over http
- added checks in "add_wishlist_profile_link()" and updated a few things
> Changed some conditions and added checks

- enhancedsteam.js
- fixed a bug where after selling a few items using Quick or Instant sell button multiple ajax requests would be issued for the same item, causing the requests to fail
> Fixed a bug with Quick and Instant sell buttons

- css/enhancedsteam.css
- enhancedsteam.js
- fixed a bug with activity hightlights where text would still get a border just because it was checked whether it needs to be highlighted
- added an extra class so we know which item was checked or highligted already
- added a variable check for "appid"
> Tweaked highlights

- enhancedsteam.js
- removed  fix_profile_image_not_found()
- renamed fix_wishlist_image_not_found() to fix_app_image_not_found()
> Removed fix_profile_image_not_found() as it was redundant

- enhancedsteam.js
- optimized and cleaned the code a bit
- fixed #1111
> add_total_drops_count() optimizations

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
When an error occurs a log of what request failed can be viewed by hovering the progress bar.
By default, the url requested and the error code and message will be shown, but custom error messages can also be set. There is commented out code for testing purposes, please remove it when done with it.
> Progress error log

- css/enhancedsteam.css
- enhancedsteam.js
- fixed a bug where unwanted elements such as screenshots would get
highlighted
> Fixed bug with recommendations highlights on store front

- enhancedsteam.js
- fixed a bug where invalid empty data was being returned from
**store.steampowered.com/dynamicstore/userdata/** for unknown reasons (as if
the user was logged out) and later cached resulting in apps not being
highlighted properly.
Now the cached data is returned immediately if available and updated in the
background if needed. On update the data is checked if empty.
> Fix for empty dynamicstore data

- enhancedsteam.js
The bug was reported on ES sub-reddit at
https://www.reddit.com/r/EnhancedSteam/comments/4z7vav/bug_report_problem_w_wishlist_total/
> Fixed a bug with wishlist total

- css/enhancedsteam.css
- enhancedsteam.js
- optimized and simplified some code
- sorting by listing date works corectly now
- offloaded sort indicators to CSS
> Market sorting code optimizations

- enhancedsteam.js
- localization/en/strings.json
* Fixes `Starting at: undefined` when viewing an item in other user's inventory for which there are no listings available
> Handle "undefined" prices when there are no listings for an item

- css/enhancedsteam.css
- enhancedsteam.js
- removed some unnecessary vars
- simplified a few things, including how CSS styles are applied
> Tidying groups_leave_options()

- enhancedsteam.js
- options.html
- few optimizations in add_empty_wishlist_buttons()
- moved "_Show "Empty Wishlist" button_" under the "General" tab in
options
> add_empty_wishlist_buttons() optimizations

- css/enhancedsteam.css
- enhancedsteam.js
- fixed a small issue with the media slider in Workshop after it was expanded.
Some  images would get distorted if they didn't have an aspect ratio or
size that would've filled the slider
> media_slider_expander() optimizations

- enhancedsteam.js
> Fixes various issues with sums on market front page

- enhancedsteam.js
Bugfix for #1177 
On reload, checkboxes and tag labels should now display correctly
> Exclude Tags: bugfix

- enhancedsteam.js
ES's Twitch channel API returns empty responses at the moment resulting in errors. Just added a check for it to avoid them...
> FIX: Twitch channel API empty response errors

- css/enhancedsteam.css
- enhancedsteam.js
(_things were way over complicated in here_)
> UPDATE: Rewrote the code for ES dropdown menu

- enhancedsteam.js
- fixed a bug when a (bugged?) game inventory didn't show any items count
> FIX: Bug in hide_empty_inventory_tabs()

- enhancedsteam.js
- fixed a bug where ES would break when accessing paginated badge pages
- simplified a few things and fixed a regex typo
> FIX: Bugs in badge sorting options

- enhancedsteam.js
- fixed a posibile error reported at http://steamcommunity.com/groups/enhancedsteam/discussions/0/215439774872684119/
- simplified function
> FIX: Possible add_dlc_page_link() bug

- enhancedsteam.js
Use the steam tooltips instead of titles. It was confusing users.
> UPDATE: use steam tooltips instead of titles

- enhancedsteam.js
- fixed a bug where the background or style would still be present after removing them due to cache not being cleared/refreshed
> FIX: Custom ES style and background cache bug

- enhancedsteam.js
- if a profile is private we shouldn't apply ES custom styling on it (_the change is only visual since this information can still be retrieved_)
> FIX: Leaking custom ES profile styling on private profiles

- enhancedsteam.js
Reported at
http://steamcommunity.com/groups/enhancedsteam/discussions/0/1843493219425716513/
> FIX: Broken steam item prices in other's inventory

- enhancedsteam.js
- fixed a bug in Store's main menu where the dropdown wouldn't get hidden out mouse out
> FIX: Persistent Store menu dropdown

- enhancedsteam.js
add_badge_page_link on market
https://github.com/jshackles/Enhanced_Steam/issues/1228
> Added suggestion #1228

- css/enhancedsteam.css
_Bug reported by @thomas-ashcraft  in #1256_
> FIX: Web Chat scrollbar not sticking to the bottom

- enhancedsteam.js
- fixed an error when viewing other market pages than card pages
> FIX: Bug in add_badge_page_link()

- css/enhancedsteam.css
- enhancedsteam.js
Fixes issues with the content and header not being properly centered when the sidebar is disabled.
> FIX: Sidebar toggling issues

- enhancedsteam.js
_forgot to change a few things in previous PR, my bad..._
> Fixed class toggling not working

- css/enhancedsteam.css
- enhancedsteam.js
- fixed a bug with the Customize button dropdown not being positioned properly in some situations
- simplified and optimized some code
> FIX: Customize button dropdown positioning

- css/enhancedsteam.css
- fixed page background image not being centered at lower resolutions when sidebar is disabled
> Fixed page background not being centerd

- css/enhancedsteam.css
> Improved ratings visibility against background

- enhancedsteam.js
- fixed a issue where Custom Reviews weren't displayed properly after being toggled on/off
- fixed Custom Reviews text in the dropdown to not include the "Learn More" words
> Fixed a few Customer Reviews toggling issues

- css/enhancedsteam.css
- enhancedsteam.js
- cleaned and optimized the code in `customize_home_page()` (leading to considerably less lines of code)
- added a function to return only the first level text from an element
_TODO: Same thing for `customize_app_page()`_
> UPDATE: Home page customization code cleanup

- css/enhancedsteam.css
- css/store.steampowered.com/store_front.css
- manifest.json
- fixed CSS for centering Store's front page being applied on other pages such as apps pages and steamcommunity.com
> FIX: CSS styles being applied in unwated areas

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
- added the option to sort by User reviews score
- removed scores retrieval limit caused by URL length constrains
- fixed score images not being displayed properly while browsing over HTTPS
- fixed a score rounding issue where there would be several trailing digits
- several small optimizations to wishlist_add_ratings()
> ADD: Sort by User reviews

- css/enhancedsteam.css
- enhancedsteam.js
- optimized the code so there is less repetitive code inserted into the page for less memory usage
- renamed duplicate function name
> UPDATE: Code for "Add to cart" button in wishlist

- enhancedsteam.js
- redone customize_app_page()
- fixed a few more cases of mixed-content warnings
> UPDATE: Redone customize_app_page()

- css/enhancedsteam.css
_the icons size is not closer to each other_
> FIX: Icons font size for Popular Items toggle

- enhancedsteam.js
- fixed a bug where 'Add to Cart' button would be shown on apps marked as 'Free'
> FIX: 'Add to Cart' button on 'Free' apps

- enhancedsteam.js
- streamlined the code so is less repetitive and made a few small optimizations
> UPDATE: add_steamrep_api() code

- enhancedsteam.js
- with the latest Market changes the sorting no longer worked as intended
> FIX: Listings sorting

- enhancedsteam.js
Fixes quite a few cases where items with '#' or other characters in the name get incorrect links
> Encode hash_name with encodeURIComponent

- enhancedsteam.js
- fixed a bug where the buttons for sorting listings would be removed
after changing market items per page
> FIX: Missing listings sort buttons

- enhancedsteam.js
- refactored the code so there are considerably less loops, making the code  faster and more accurate when looking for cards data 
- fixes #1340
> UPDATE: add_gamecard_market_links() code

- enhancedsteam.js
- refactored the code to speed up things, first by checking user's
settings and only if highlighting is enabled get to work, and second by
reducing the ammount of loops needed to match a hash name
> UPDATE: highlight_market_items() code

- enhancedsteam.js
I don't really understand why the previous code didn't work, but this fixes the issue.
> FIX #1378 (button to toggle review section on app page doesn't work)

- enhancedsteam.js
_in the latest version I was attempting to fix a pause and introduced another... sorry about that_
Fixed #1390 and cleaned and optimized a few lines of code.
> FIX: #1390

- enhancedsteam.js
_Reported at http://steamcommunity.com/groups/enhancedsteam/discussions/0/1457328846184361655/_
> FIX: Steam Card Exchange links toggle option

- css/enhancedsteam.css
- enhancedsteam.js
- img/clippy.svg
- manifest.json
- added a button to copy profiles permalink with one click
_["Copy to clipboard" icon](https://octicons.github.com/icon/clippy/) (c) GitHub, Inc. [licensed under SIL OFL 1.1](https://github.com/primer/octicons#license)._
> ADD: Profile permalink copy button

- enhancedsteam.js
> FIX: User reviews tooltip

- enhancedsteam.js
- fixed an error where "app/" wasn't removed from "subid" var, causing ES to break
> FIX: Pricing history variable error

- enhancedsteam.js
> ADD: Store page link on badge pages

- enhancedsteam.js
- fixed a bug where the HD buttons for videos were missing. This was caused by some changes to the player done by Valve in order to improve performance
- removed Valve's auto switch to HD when fullscreening a video, as requested here http://steamcommunity.com/groups/enhancedsteam/discussions/0/1471966894868105830/
> FIX: HD toggle button missing on videos

- enhancedsteam.js
We now also compare the **_profile_path_** to make sure currently logged in user data matches.
_This is a quick fix, a proper one would be done by making use of ES's
storage, however, chrome.storage.local unlike localStorage is not
synchronous, and so all functions depending on signed_in_promise() would
need to wrapped and deffered until signed_in_promise() completes.
And since this will need some extended testing we'll postpone until we
decide to move functions in sepparate files._
> FIX: signed_in_promise() login check bug

- enhancedsteam.js
Before: https://i.imgur.com/XeKFhPw.png
After: https://i.imgur.com/ULpMxMX.png
> FIX: Unreleased games show NaN% in wishlist scores

- enhancedsteam.js
> REMOVED: Market games list collapse

- css/enhancedsteam.css
- enhancedsteam.js
- localization/en/strings.json
There's one problem I'm not sure how to solve and that is how to display the input and the currency symbol. I've come up with two solutions, but either one of those only works for one position of the currency symbol (before/after the input). Any ideas?
> ADD: Custom gift card amount

- enhancedsteam.js
> Skip "" when activating multiple keys

- css/enhancedsteam.css
- enhancedsteam.js
Simplified and optimized the code.
> UPDATE: add_wishlist_hover() code

- css/enhancedsteam.css
- enhancedsteam.js
Made the progress bar crossbrowser compatible so it looks the same in
all browsers. (Tested in Firefox and Chrome)
> FIX: Progress bar crossbrowser compatibility

- css/enhancedsteam.css
- css/steamcommunity.com/steam_store_hover.css
- enhancedsteam.js
- manifest.json
- Fix styling from store.css being applied on other elements making them look bad.
- Fix empty hover container when no data is returned
> FIX: Hover CSS styling

- enhancedsteam.js
Resolves jshackles/EnhancedSteam#1469
> Resize the Activate Multiple Key modal dialog

- enhancedsteam.js
- added the ability to toggle video player fullscreen with double clicks
- fixed a bug where the HD control wasn't added on the first video if
Autoplay was ON
> ADD: Video player fullscreen toggle with dblclick

- enhancedsteam.js
Fixes #1578 
Also remove code that addressed an issue which was caused by Valve not using HTTPS all over.
> FIX: Chat dropdown

- enhancedsteam.js
- js/options.js
- localization/en/strings.json
- options.html
This has been requested several times in the past.
fixes #1593 
fixes #1549
> ADD: Progress bar toggle
